apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: node-demo
  labels:
    app: node-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-demo
  template:
    metadata:
      labels:
        app: node-demo
    spec:
      containers:
        - name: node-demo
          image: nikkinicholasromero/node-demo:latest
          ports:
            - containerPort: 8080
