apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: node-demo
  labels:
    app: node-demo
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: node-demo
